server:
  port: 8081

spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_user?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: hhs123456789
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

seata:
  tx-service-group: my-tx-group
  service:
    vgroup-mapping.my-tx-group: seata-server
    grouplist.seata-server: 127.0.0.1:8091
  enabled: true