server:
  port: 10909
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://localhost:8848/nacos
    routeAuth:
      enable: true
      username: nacos
      password: nacos
    routes:
      - name: service-user
        serviceName: service-user
        location: /v2/api-docs?group=default
        servicePath: /order/prod