server:
  port: 10909
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://localhost:8848/nacos
    routeAuth:
      enable: true
      username: nacos
      password: nacos
    routes:
      - name: service-user
        serviceName: service-user
        location: /v2/api-docs?group=default
      - name: service-room
        service-name: service-room
        location: /v2/api-docs?group=default
      - name: service-point
        service-name: service-point
        location: /v2/api-docs?group=default
spring:
  application:
    name: service-doc
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848